"""empty message

Revision ID: 0811697ce309
Revises: ad1035a572c2
Create Date: 2020-11-13 02:10:39.107922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0811697ce309'
down_revision = 'ad1035a572c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_data', 'bot')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_data', sa.Column('bot', mysql.VARCHAR(length=60), nullable=True))
    # ### end Alembic commands ###
