"""empty message

Revision ID: 086fb6ef2249
Revises: e37c0a5e7125
Create Date: 2020-11-24 09:26:45.961044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086fb6ef2249'
down_revision = 'e37c0a5e7125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('paid', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'paid')
    # ### end Alembic commands ###
