"""empty message

Revision ID: 82df837888be
Revises: 086fb6ef2249
Create Date: 2020-11-24 09:27:02.090068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82df837888be'
down_revision = '086fb6ef2249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'paid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('paid', mysql.VARCHAR(length=80), nullable=True))
    # ### end Alembic commands ###
