"""empty message

Revision ID: 9ff6dcaf9761
Revises: e38bd7ed90f4
Create Date: 2020-11-28 23:57:06.816319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ff6dcaf9761'
down_revision = 'e38bd7ed90f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet_49ja', sa.Column('bet9ja_username', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bet_49ja', 'bet9ja_username')
    # ### end Alembic commands ###
