"""empty message

Revision ID: ad1035a572c2
Revises: a4b881535c71
Create Date: 2020-11-13 01:31:53.926717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad1035a572c2'
down_revision = 'a4b881535c71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_data', sa.Column('bot', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_data', 'bot')
    # ### end Alembic commands ###
