"""empty message

Revision ID: cf860281160b
Revises: d8aafd6df92c
Create Date: 2020-11-24 09:19:28.978499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf860281160b'
down_revision = 'd8aafd6df92c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('cus_codes', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'cus_codes')
    # ### end Alembic commands ###
