"""empty message

Revision ID: e37c0a5e7125
Revises: cf860281160b
Create Date: 2020-11-24 09:20:27.079983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e37c0a5e7125'
down_revision = 'cf860281160b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'cus_codes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('cus_codes', mysql.VARCHAR(length=30), nullable=True))
    # ### end Alembic commands ###
