"""empty message

Revision ID: e38bd7ed90f4
Revises: 82df837888be
Create Date: 2020-11-28 23:01:48.511128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e38bd7ed90f4'
down_revision = '82df837888be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet_49ja', sa.Column('is_building', sa.Boolean(), nullable=True))
    op.drop_column('bet_49ja', 'is_updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet_49ja', sa.Column('is_updated', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('bet_49ja', 'is_building')
    # ### end Alembic commands ###
