"""empty message

Revision ID: f352a8075324
Revises: 9ff6dcaf9761
Create Date: 2020-11-29 11:22:05.037734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f352a8075324'
down_revision = '9ff6dcaf9761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet_49ja', sa.Column('bot_mimetype', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bet_49ja', 'bot_mimetype')
    # ### end Alembic commands ###
